### ISSUE TITLE
Add 'Selector format' from scss-lint

### ISSUE THREAD

**Issue by dnamsons** [sds/haml-lint#284]
I think that it would be beneficial to add the option to add naming conventions, like in scss-lint

**Comment by michaelherold** [comment]
Are you thinking that this would be similar to [IdNames](https://github.com/brigade/haml-lint/tree/master/lib/haml_lint/linter#idnames), but for CSS classes?

If so, the tricky part of this will likely be that you can specify CSS classes in two forms:

```haml
#my-div.my-css-class

-# vs

#my-dev{class: 'my-css-class'}
```

The first form should be somewhat easy, the latter form might be a little harder.

---

It occurs to me: should this truly be enforced at the Haml level? Since at the Haml level you refer to classes that you define in CSS/Sass, it feels like it might be more hassle than value to enforce it on the Haml side. It seems like you should enforce that on the CSS/Sass side and then Haml can use what you enforce as a contract.

What do you think?

**Comment by mtancoigne** [comment]
Isn't it the same with ids ? `#my-id`, `%div{id: 'my-id'` and `%div{id: "some-#{dynamic}-id"` ?
