### ISSUE TITLE
require `haml_lint/spec`

### ISSUE THREAD

**Issue by LukeeeeBennett** [sds/haml-lint#302]
I really like the shared context and matchers for testing linters in the `haml-lint` repo. I would like to use them for a custom linter's spec and for now have had to copy them over to my repo.

Can these be included in the gemspec files? I am relatively new to gemfiles and ruby in general so sorry if there is already a way to do this that I have missed. If it cannot be packaged in the gem, or this is not ideal, would you accept a repo under your namespace to make spec/support reusable?

**Comment by sds** [comment]
Open to a pull request adding support for this!

You'll need to move the files from `spec/support` to `lib/haml_lint/spec` and wrap them in appropriate module declarations so they don't pollute the global namespace when `require`d. 

This will ensure they are included in future published gems, since they'll be picked up by this line in the gemspec: https://github.com/sds/haml-lint/blob/024c773667e54cf88db938c2b368977005d70ee8/haml_lint.gemspec#L22

You'll then be able to require them using:
```ruby
require 'haml_lint/spec/...'
```
...or similar.

There are some other details to figure out, but happy with this approach directionally.
