### ISSUE TITLE
Request for opinions about RuboCop's template support API

### ISSUE THREAD

**Issue by r7kamura** [sds/haml-lint#379]
## About

I'm now working on adding an API to RuboCop to support templates such as ERB, Haml and Slim.

- https://github.com/rubocop/rubocop/pull/10839

I'm curious to hear your thoughts on adding such API to the RuboCop side., so I created this Issue to get your feedback about that. If you have any questions, requests or ideas, please let me know.

## Schedule

I hope to finish collecting feedback by **November 30, 2022**, and then release the API (maybe in January 2023 or so).

## Related issues

Sorry for sending similar Issues, but I wanted to hear opinions also from the user side, so I created an Issue for each tool.

- https://github.com/Shopify/erb-lint/issues/274
- https://github.com/sds/slim-lint/issues/142

**Comment by r7kamura** [comment]
This API also supports autocorrection, which may be relevant to the following Issue / Pull Requests:

- https://github.com/sds/haml-lint/pull/346
- https://github.com/sds/haml-lint/issues/217

cc: @MaxLap

**Comment by MaxLap** [comment]
Very nice to see work for such support in RuboCop.

One thing of note about Haml versus ERB is that its structure follow's Ruby's code a lot. So if you look at the tests in my PR, there are things like merging 2 lines together, which can mean changing indentation. Examples of that are [here](https://github.com/sds/haml-lint/blob/6332ed6d933df14acf5848268239f7c0a37eb0e8/spec/haml_lint/linter/rubocop_autocorrect_examples/changing_indentation_examples.txt).. (Each `!!!` starts a new example, separated in parts by `---`. Compare the first to the last part of the examples).

I don't believe this kind of things can't be done by your system, because it works on a per-snippet basis. In Haml, 2 consecutive lines of ruby code may be in a filter (`:ruby`), silent (each prefixed by a `-`), outputting (each prefixed by a `=`). Since your system is the one doing the file editing, it's impossible to tell Rubocop how to handle those.

So right now, if I ever finish this autocorrect PR, it couldn't use your system. My PR works by rewriting the entire HAML file to a ruby file with some separators to be able to re-separate the chunks. (Those are the intermediary parts in the examples I linked above)

Doing things this way allows for way more Rubocop rules to be enforced, including things such as unused variables, which couldn't be considered in a vacuum.

Sorry, I don't know what to suggest that would be helpful, in parts because I haven't touched that PR in too long.

**Comment by r7kamura** [comment]
Good information. Thank you very much!

I hadn't read up on it in much detail, but I see that your implementation also supports chunks compositing. That's great 💯 
As you said, my implementation is quite naive and does not support such features. I wish I had a better way to do it, but so far I haven't come up with one.

```haml
- if foo
  - if bar
    - do_something
```

For example, given the code above, my implementation would extract the following three fragments and run RuboCop for each one separately, then apply autocorrection on each fragment ranges.

```ruby
foo
```

```ruby
bar
```

```ruby
do_something
```

Ideally, the first haml example would be converted as follows,

```haml
- if foo && bar
  - do_something
```

but in practice, there may be unrelated code in between, and indentation needs to be adjusted accordingly when dealing with autocorrection. I love that you're taking on that challenge.

**Comment by sds** [comment]
Thanks for soliciting feedback! And thanks Maxime for sharing some thoughts.

I'm going to close as it seems this thread has served its purpose.
