### ISSUE TITLE
Haml-lint is running rubocop to lint JavaScript regex

### ISSUE THREAD

**Issue by pedrobahamondes** [sds/haml-lint#438]
I reduced the example to a minimum, but essentially this shows that rubocop is being used to lint JavaScript regular expressions:
![image](https://github.com/sds/haml-lint/assets/94003400/87e8f60c-f423-44e5-9564-828f53dc0e9f)

Observation: The regex in the image is `/^\d*\.?\d*$/`. There, `\.` is not a redundant escape (although the same result can be achieved with the longer expression `[.]`), since `.` matches any character.

In any case, there are differences between JavaScript and Ruby regex. Here are some differences according to ChatGPT:
> 1. String Delimiters:
>
> JavaScript: Enclosed in forward slashes (/.../), like /pattern/flags.
>
>Ruby: Often enclosed in forward slashes (/.../), but can also use %r{...} or %r|...| as delimiters.
>
>2. Flag Syntax:
>
>JavaScript: Flags are appended after the closing slash, like /pattern/g.
>
>Ruby: Flags are provided as separate arguments or with (?flags) inline modifier, like /pattern/i or /pattern(?i)/.
>
>3. Named Capturing Groups:
>
>Ruby: Supports named capturing groups using (?<name>...).
>
>JavaScript: Does not natively support named capturing groups, but you can use numbered capturing groups.
>
>4. Escape Characters:
>
>Ruby and JavaScript handle certain escape sequences differently. For example, \b is a word boundary in JavaScript and a backspace character in Ruby.
>

I don't know if this is an issue with Haml-lint or Rubocop, but I would like a turnaround other than `-# rubocop:disable Style/RedundantStringEscape` for expressions where the lint fails to work as it should. If this is a Rubocop issue when employing haml-lint, please let me know and I'll post this there.

Thank you!

**Comment by MaxLap** [comment]
Hello, thanks for the great report! The problem is clearly on Haml-lint's side.

What's actually happening I think is that when Haml-lint encounters a HAML filter, it treats its content as a here-doc. This is so that interpolation can be handled by Rubocop along with all of its context (and it felt easier).

So Rubocop sees a `\.` in the here-doc and whines since it's not a valid escape. The problem would happen if you had a string or a comment that contains `\.`

I will have to dig into this a bit to figure out what can be done. Might have to change the whole :filter handling.

Shouldn't be too long before I get to this (hopefully tonight), but In the meantime, yeah, `-# rubocop:disable Style/RedundantStringEscape` is kind of the only option, sorry.
