### ISSUE TITLE
Allow Haml 6.3

### ISSUE THREAD

**Issue by tagliala** [sds/haml-lint#458]

**Comment by robbl-as** [comment]
To me, the problem is, that we can update haml-lint or haml, but not execute haml-lint afterwards. it Isn't there a solution to use gemfile dependencies to communicate compatibility? Is there a reason, why this is not done, yet? The advantage would be that versions would always be compatible with each other, right?

**Comment by tagliala** [comment]
Here it is the reason why at the moment Haml is updatable but Haml lint isn't 

https://github.com/sds/haml-lint/pull/447#issue-1920816795

(TL;DR: haml-lint should not prevent the update of a production library. It is not ideal, but it is better to fail in this way)

**Comment by tagliala** [comment]
Also, there are breaking changes and deprecation between minor version of Haml. In this case, we have this: https://github.com/haml/haml/blob/main/CHANGELOG.md#630
