### ISSUE TITLE
RuboCop: Lint/Syntax: unexpected token tSYMBOL and kEND

### ISSUE THREAD

**Issue by linxola** [sds/haml-lint#474]
Hello,
I have encountered what I assume is a bug when using new Ruby's hash syntax at the end of the `=` tag's line with the other `=` line following it.

The problem lines:
```
= render 'devise/shared/error_messages', resource:
= f.hidden_field :reset_password_token
```

The errors I get:
- RuboCop: Lint/Syntax: unexpected token tSYMBOL (on the line with `= f.hidden_field :reset_password_token`)
- RuboCop: Lint/Syntax: unexpected token kEND (at the end of `form_for` block)

The full view (it's devise's password update view):
```
%h2 Change your password

= form_for(resource, as: resource_name, html: { method: :put },
                     url: password_path(resource_name)) do |f|
  = render 'devise/shared/error_messages', resource:
  = f.hidden_field :reset_password_token

  .field
    = f.label :password, 'New password'
    %br/
    - if @minimum_password_length
      %em (#{@minimum_password_length} characters minimum)
      %br/
    = f.password_field :password, autofocus: true, autocomplete: 'new-password'

  .field
    = f.label :password_confirmation, 'Confirm new password'
    %br/
    = f.password_field :password_confirmation, autocomplete: 'new-password'

  .actions
    = f.submit 'Change my password'

= render 'devise/shared/links'
```

Versions I use:
```
haml-lint 0.53.0
rubocop 1.58.0
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
```

Also, this error can be omitted with inserting some text or comment between the problematic lines.

**Comment by sds** [comment]
Are you sure `resource:` has no arguments after it? What is the expected behavior when the value is omitted? Treat as `nil`?

**Comment by MaxLap** [comment]
It's a shortcut to using the variable/method with the same name. Like in JS.

I'm looking into it.

**Comment by MaxLap** [comment]
So thanks for the report. Unfortunately, I would say the problem is in your code.

From my testing, this (your code) is not valid ruby code:

```
render 'devise/shared/error_messages', resource:
f.hidden_field :reset_password_token
```

Try it in a file and try to run `rubocop` or even just plain `ruby` on it. Same error.

Or try it in an irb console (with a def, so that it's all treated at once):

```
def foo
  render 'devise/shared/error_messages', resource:
  f.hidden_field :reset_password_token
end
```

It will get refused. The code might work in HAML, and in the previous version of haml-lint. But that's just an unintended side-effect of how the code is processed (HAML adds lots of parentheses and HAML-lint used to process line by line).

It feels weird to use the shortcut of not specifying a variable without having parentheses around the call. It really feels ambiguous if the result of the next line should be used or the default variable. And this error is proof that it's ambiguous.

Your solution is to put parentheses: `render('devise/shared/error_messages', resource:)`

Regards,

**Comment by sds** [comment]
Going to close as a question that has been answered. Thanks!
