### ISSUE TITLE
More severity levels

### ISSUE THREAD

**Issue by skateman** [sds/haml-lint#85]
We're proudly using haml-lint in our [bot](https://github.com/ManageIQ/miq_bot) bot but we would like to use the same severity levels as [RuboCop](https://github.com/bbatsov/rubocop#severity) does. Would you accept a pull request which implements this enhancement?

**Comment by sds** [comment]
Hey @skateman,

I think adding severity levels is inevitable, although I would keep it simple and only have `warning` and `error`, rather than the ones that `RuboCop` uses (`lint`, `cop`, `fatal`, etc.)

Most of the plumbing supporting this is already in place, so it should be easy to add. Feel free to submit a pull request, otherwise we'll get to it when we can.
